pipeline:
  context:
    topic: "artificial intelligence with crypto"
    num_results: 5
    model_name: "llama2"

  steps:
    - name: "web_search"
      type: "WebSearch"
      query: "latest developments in {context.topic}"
      search_type: "serper"
      num_results: "{context.num_results}"

    - name: "summarize_findings"
      type: "RunInference"
      source: "ollama"
      model_name: "llama2"
      prompt: "Summarize the latest developments in {context.topic} based on the following information: {steps.web_search}"

    - name: "text_to_speech"
      type: "TextToSpeech"
      text: "{steps.summarize_findings}"
      data_path: "/app/output/summary_audio.wav"

    - name: "generate_image"
      type: "GenerateImage"
      prompt: "A futuristic representation of {context.topic}"
      data_path: "/app/output/ai_developments.png"
      image_params:
        num_inference_steps: 50
        guidance_scale: 7.5

    - name: "final_report"
      type: "RunInference"
      source: "ollama"
      model_name: "llama2"
      prompt: "Create a final report on {context.topic} incorporating the following elements:\n1. Web search results: {steps.web_search}\n2. Summarized findings: {steps.summarize_findings}\n4. Generated image description: A futuristic representation of {context.topic}\n5. Transcription accuracy check: Compare the original summary with the transcribed text and comment on any discrepancies."
      result_path: "/app/output/final_report.txt"
